name: Go

on:
  workflow_dispatch: 

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Fix workspace ownership
      run: sudo chown -R vscode:vscode $GITHUB_WORKSPACE

    - name: Perform tasks inside DevContainer
      uses: devcontainers/ci@v0.2
      with:
        noCache: true
        runCmd: |
          set -e
          echo "[INFO] whoami: $(whoami)"
          echo "[INFO] id (vscode): $(id vscode)"
          ls -ltrhg
          echo "[INFO] DevContainer Ready"
          echo "[INFO] Running tasks to test, generate coverage report and build"
          if ! task all; then
            echo "[ERROR] Failed to properly run the tasks"
            exit 1
          fi