name: Go

on:
  workflow_dispatch: 

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Perform tasks inside DevContainer
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          set -e
          echo "[INFO] DevContainer Ready"
          echo "[INFO] Running tasks to test, generate coverage report and build"
          if ! task all; then
            echo "[ERROR] Failed to properly run the tasks"
            exit 1
          fi